export enum Errors {
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  VALIDATION_NAME = 'MESSAGE_VALIDATION_NAME',
  VALIDATION_EMAIL = 'MESSAGE_VALIDATION_EMAIL',
  VALIDATION_MESSAGE = 'MESSAGE_VALIDATION_MESSAGE',
  VALIDATION_TYPE = 'MESSAGE_VALIDATION_MESSAGE',
}
